[package]
edition = "2021"
license = "MIT OR Apache"
name = "static-router"
version = "0.1.0"

[dependencies]
axum = "0.5"
static-router-macros = { path = "../static-router-macros" }
tower-http = { version = "0.3", features = ["fs"] }
